# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build TFM_UOC
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # if you add permissions here this needs to be done in the TFM_UOC-orchestration.yaml as well
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.16.0

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install
          npm run build

      - name: Setup composer
        uses: php-actions/composer@v6
# uncomment the following lines if you want to add environment variables for this step
#        env:
#          MY_ENV_VAR: value-for-my-env-var
#          MY_SECRET_ENV_VAR: ${{ secrets.MY_SECRET }} # here you can find information how to create secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets
        with:
          php_version: '8.2.0'

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 918ff679-1647-4907-90ab-d7978ca6fecb
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/TFM_UOC/config.yaml
          action: upload
